// Contenuto completo del test — le risposte corrette NON vengono mai inviate al client.
const content = {
  title: "🇮🇹 Test di LIVELLO A2",
  totalMinutes: 90,
  totalPoints: 100,
  intro: {
    firstParagraphUk: "Простір italica вітає тебе на фінальному тестуванні курсу A2!",
    bodyIt: [
      "Перш за все — видихни 😌 Це не іспит, який має тебе злякати, а шанс подивитися на себе збоку і зрозуміти, скільки всього ти вже вмієш. Згадай свій перший урок: тоді навіть \"Come ti chiami?\" здавалося космічною фізикою, а зараз ти читаєш, слухаєш, говориш і будуєш речення італійською. Це реально крутий шлях, і ти вже на фініші!",
    ],
    howItWorksTitle: "Як проходитиме тест?",
    howItWorks: [
      "Він складається з 7 частин (читання поділено на два тексти) і займе приблизно 90 хвилин.",
      "Також на тебе чекають ще дві частини: письмова — де треба самостійно написати текст, і усна — де треба записати голосову відповідь. Перед початком сайт попросить дозвіл на мікрофон, це нормально, нічого страшного 🎙️",
      "Читай завдання уважно, подумай над відповіддю — і тільки тоді рухайся далі. Поспіх тут не потрібен.",
    ],
    beforeStartTitle: "Перед початком",
    beforeStart: [
      "знайди спокійне місце, де тебе ніхто не смикатиме;",
      "переконайся, що інтернет не підведе в найважливіший момент;",
      "видихни ще раз — ти знаєш набагато більше, ніж тобі здається.",
    ],
    closing: "❤️ Ми віримо в тебе! Не переживай через окремі запитання — цей тест не про ідеальність, а про твій прогрес. А прогрес у тебе є, і чималий.",
    signOff: "In bocca al lupo! 🇮🇹",
  },
  parts: [
    {
      id: "grammatica",
      number: 1,
      title: "Grammatica",
      kind: "parte scritta",
      type: "mcq",
      points: 20,
      instructions: "Scegli la risposta corretta (a, b, c o d) per completare ogni frase. Ogni risposta corretta vale 1 punto.",
      items: [
        { id: "g1", text: "Ogni mattina io __________ alle 7:00. (svegliarsi)", options: ["ti svegli", "mi sveglio", "mi sveglia", "svegliarmi"], correct: 1 },
        { id: "g2", text: "Marco __________ giocare a calcio, ma oggi è stanco. (volere)", options: ["vuoi", "vogliamo", "vogliono", "vuole"], correct: 3 },
        { id: "g3", text: "Ieri sera noi __________ al cinema. (andare)", options: ["siamo andati", "abbiamo andato", "hanno andato", "sono andati"], correct: 0 },
        { id: "g4", text: "Non ho tempo, __________ studiare stasera. (dovere)", options: ["deve", "dobbiamo", "devo", "devono"], correct: 2 },
        { id: "g5", text: "In cucina __________ quattro sedie e un tavolo.", options: ["c'è", "ci sono", "è", "sono"], correct: 1 },
        { id: "g6", text: "Compro __________ mele al mercato.", options: ["delle", "del", "dei", "della"], correct: 0 },
        { id: "g7", text: "Questa camicia è troppo grande, ne vorrei una più __________.", options: ["piccolo", "piccoli", "piccole", "piccola"], correct: 3 },
        { id: "g8", text: "Da bambino, io __________ sempre con mio fratello. (giocare)", options: ["giocai", "gioco", "giocavo", "ho giocato"], correct: 2 },
        { id: "g9", text: "(Tu) __________ la finestra, per favore! (aprire)", options: ["apre", "apri", "apra", "aprono"], correct: 1 },
        { id: "g10", text: "Signora, per favore, __________ un momento! (aspettare)", options: ["aspetta", "aspettate", "aspettare", "aspetti"], correct: 3 },
        { id: "g11", text: "Per aprire un conto in banca, __________ avere un documento d'identità.", options: ["bisogna", "bisognano", "bisogni", "hai bisogno"], correct: 0 },
        { id: "g12", text: "Domani io __________ a Roma per lavoro. (andare)", options: ["andarò", "andavo", "andrò", "sono andato"], correct: 2 },
        { id: "g13", text: "Se domani __________ bel tempo, andiamo al mare.", options: ["farà", "faccia", "facesse", "fa"], correct: 0 },
        { id: "g14", text: "Non __________ (tu, aprire) la porta a sconosciuti!", options: ["Apri", "Aprire", "Apra", "Apre"], correct: 0 },
        { id: "g15", text: "Quante mele vuoi? __________ vorrei un chilo.", options: ["Ci", "Li", "Ne", "Le"], correct: 2 },
        { id: "g16", text: "Ho comprato __________ pane per la cena.", options: ["poco", "pochi", "poca", "poche"], correct: 0 },
        { id: "g17", text: "Marco è la persona __________ conosco meglio in ufficio.", options: ["chi", "cui", "quale", "che"], correct: 3 },
        { id: "g18", text: "Se __________ più tempo, viaggerei di più.", options: ["ho", "avessi", "avrò", "avevo"], correct: 1 },
        { id: "g19", text: "In Italia, __________ mangia la pasta quasi ogni giorno.", options: ["se", "ci", "si", "ne"], correct: 2 },
        { id: "g20", text: "Roma è __________ d'Italia, secondo me.", options: ["la città più bella", "il più bella", "la città bella", "la più città bella"], correct: 0 },
      ],
    },
    {
      id: "lettura1",
      number: 2,
      title: "Comprensione della lettura — Testo 1",
      kind: "parte scritta",
      type: "reading",
      points: 5,
      instructions: "Leggi il testo e indica se le affermazioni sono vere (Vero) o false (Falso). Ogni risposta corretta vale 1 punto.",
      readingTitle: "La storia di Marta",
      text: "Mi chiamo Marta e ho 29 anni. Fino a due anni fa vivevo in un piccolo paese vicino a Torino, in una casa antica con un grande giardino. Non avevo la macchina e andavo al lavoro a piedi. Lavoravo come cameriera in un ristorante del centro: l'orario era lungo e lo stipendio non era alto, ma i colleghi erano simpatici. Un giorno ho deciso di cambiare vita. Mi sono trasferita a Milano per studiare informatica. All'inizio è stato difficile: l'affitto era caro e non conoscevo nessuno. Ora invece vivo in un appartamento luminoso con due coinquilini e lavoro part-time in un'azienda tecnologica. Ogni giorno mi alzo alle sette, faccio colazione con frutta e yogurt (prima mangiavo solo un cornetto!) e vado in ufficio in metro. La sera, se ho tempo libero, vado in palestra o guardo una serie con i miei coinquilini. Il mese scorso mi sono sentita male: avevo la febbre e mal di gola. Sono andata dal medico e lui mi ha detto di stare a letto e di prendere uno sciroppo. Dopo tre giorni stavo già meglio. Il prossimo anno penso di fare un viaggio in Giappone. Ho bisogno di risparmiare un po' di soldi, ma sono sicura che sarà un'esperienza fantastica!",
      vf: [
        { id: "l1_1", text: "Marta abitava in campagna prima di trasferirsi a Milano.", correct: true },
        { id: "l1_2", text: "A Torino Marta andava al lavoro in macchina.", correct: false },
        { id: "l1_3", text: "Il primo periodo a Milano è stato facile per Marta.", correct: false },
        { id: "l1_4", text: "Adesso Marta vive da sola.", correct: false },
        { id: "l1_5", text: "Marta è andata dal medico perché aveva la febbre.", correct: true },
      ],
      open: [],
    },
    {
      id: "lettura2",
      number: 3,
      title: "Comprensione della lettura — Testo 2",
      kind: "parte scritta",
      type: "reading",
      points: 15,
      instructions: "Leggi il testo, indica se le affermazioni sono vere o false (1 punto ciascuna) e rispondi alle domande con una frase completa (2 punti ciascuna).",
      readingTitle: "Il weekend di Giulia",
      text: "Il weekend scorso Giulia è andata a trovare i suoi nonni in campagna. Sabato mattina si è svegliata presto e ha preso il treno delle 8:15 da Milano. Durante il viaggio ha letto un libro e ha mandato qualche messaggio a un'amica. Quando è arrivata, i nonni l'aspettavano alla stazione con la macchina. Il pomeriggio hanno fatto una passeggiata nel bosco vicino a casa e hanno raccolto dei funghi. La sera hanno cenato tutti insieme e la nonna ha preparato la sua famosa torta di mele. Domenica, purtroppo, Giulia si è svegliata con mal di gola e un po' di febbre, così è rimasta a letto tutta la mattina. Nel pomeriggio si è sentita meglio e, prima di tornare a Milano, ha salutato i nonni promettendo di tornare presto.",
      vf: [
        { id: "l2_1", text: "I nonni l'hanno aspettata a casa.", correct: false },
        { id: "l2_2", text: "Giulia ha preso il treno delle 8:15.", correct: true },
        { id: "l2_3", text: "Giulia è tornata a Milano senza salutare i nonni.", correct: false },
        { id: "l2_4", text: "Giulia è andata a trovare i nonni in città.", correct: false },
        { id: "l2_5", text: "La domenica Giulia si è sentita male.", correct: true },
      ],
      open: [
        { id: "l2_o1", text: "Che cosa ha fatto Giulia durante il viaggio in treno?", points: 2, sample: "Ha letto un libro e ha mandato qualche messaggio a un'amica." },
        { id: "l2_o2", text: "Che cosa hanno fatto Giulia e i nonni sabato pomeriggio?", points: 2, sample: "Hanno fatto una passeggiata nel bosco e hanno raccolto dei funghi." },
        { id: "l2_o3", text: "Che cosa ha preparato la nonna per cena?", points: 2, sample: "Ha preparato la sua famosa torta di mele." },
        { id: "l2_o4", text: "Quali sintomi ha avuto Giulia domenica mattina?", points: 2, sample: "Mal di gola e un po' di febbre." },
        { id: "l2_o5", text: "Che cosa ha promesso Giulia ai nonni prima di partire?", points: 2, sample: "Ha promesso di tornare presto." },
      ],
    },
    {
      id: "lessico",
      number: 4,
      title: "Lessico",
      kind: "parte scritta",
      type: "vf-only",
      points: 10,
      instructions: "Leggi la frase e il significato proposto della parola in grassetto. Indica se è Vero o Falso. Ogni risposta corretta vale 1 punto.",
      vf: [
        { id: "x1", text: "\"Avere bisogno di\" significa \"avere voglia di\".", correct: false },
        { id: "x2", text: "\"In ritardo\" significa \"in anticipo\".", correct: false },
        { id: "x3", text: "La \"lavastoviglie\" serve per lavare i vestiti.", correct: false },
        { id: "x4", text: "Il \"salmone\" è un tipo di verdura.", correct: false },
        { id: "x5", text: "La \"compressa\" è un medicinale liquido.", correct: false },
        { id: "x6", text: "Lo \"stipendio\" sono i soldi che si ricevono per il proprio lavoro.", correct: true },
        { id: "x7", text: "Il quartiere dove abito è molto tranquillo di notte: \"tranquillo\" significa \"rumoroso\".", correct: false },
        { id: "x8", text: "Le \"ferie\" sono i giorni obbligatori di lavoro.", correct: false },
        { id: "x9", text: "\"Prenotare un albergo\" significa \"riservare in anticipo un albergo\".", correct: true },
        { id: "x10", text: "\"Basso\" è il contrario di \"alto\".", correct: true },
      ],
    },
    {
      id: "uso",
      number: 5,
      title: "Uso della lingua",
      kind: "parte scritta",
      type: "fillin",
      points: 15,
      instructions: "Completa le frasi con la forma corretta del verbo, del pronome o della parola indicata tra parentesi. Ogni risposta corretta vale 1 punto.",
      items: [
        { id: "u1", text: "Ogni giorno io __________ (alzarsi) alle 7.", accepted: ["mi alzo"] },
        { id: "u2", text: "Ieri noi __________ (mangiare) una pizza buonissima.", accepted: ["abbiamo mangiato"] },
        { id: "u3", text: "Da bambina, io __________ (abitare) in un piccolo paese.", accepted: ["abitavo"] },
        { id: "u4", text: "__________ (tu / potere) aiutarmi con le valigie?", accepted: ["puoi"] },
        { id: "u5", text: "Domani loro __________ (partire, futuro semplice) per le vacanze.", accepted: ["partiranno"] },
        { id: "u6", text: "Signora, __________ (Lei / accomodarsi), prego!", accepted: ["si accomodi"] },
        { id: "u7", text: "«Hai visto Marco?» «Sì, __________ ho visto ieri.» (pronome)", accepted: ["lo"] },
        { id: "u8", text: "«Quante lingue parli?» «__________ parlo due.» (pronome)", accepted: ["ne"] },
        { id: "u9", text: "__________ (bisognare) prenotare il tavolo prima di andare al ristorante.", accepted: ["bisogna"] },
        { id: "u10", text: "Se io __________ (avere) più soldi, comprerei una casa più grande.", accepted: ["avessi"] },
        { id: "u11", text: "In questo ristorante __________ (mangiare) molto bene.", accepted: ["si mangia"] },
        { id: "u12", text: "Marco è più alto __________ suo fratello. (comparativo)", accepted: ["di"] },
        { id: "u13", text: "Se domani farà bel tempo, noi __________ (andare) al mare.", accepted: ["andiamo", "andremo"] },
        { id: "u14", text: "Non __________ (tu / parlare) così forte, per favore!", accepted: ["parlare"] },
        { id: "u15", text: "(Tu, prendere) __________ l'ombrello! Oggi pioverà.", accepted: ["prendi"] },
      ],
    },
    {
      id: "scritta",
      number: 6,
      title: "Produzione scritta",
      kind: "parte scritta",
      type: "writing",
      points: 20,
      instructions: "Scegli UN argomento tra i seguenti e scrivi un testo di almeno 80–100 parole.",
      topics: [
        "Racconta cosa hai fatto durante l'ultimo weekend.",
        "Descrivi come stai adesso (fisicamente ed emotivamente) e spiega perché.",
        "Spiega cosa pensi di fare durante le prossime vacanze.",
        "Descrivi la tua casa o il tuo quartiere e spiega perché ti piace o non ti piace.",
        "Racconta un'esperienza di viaggio che ricordi bene e spiega perché è stata importante per te.",
      ],
      rubric: [
        { key: "contenuto", name: "Contenuto e pertinenza al tema", max: 5 },
        { key: "grammatica", name: "Correttezza grammaticale", max: 5 },
        { key: "lessico", name: "Lessico appropriato e vario", max: 5 },
        { key: "coerenza", name: "Coerenza e coesione del testo", max: 5 },
      ],
    },
    {
      id: "orale",
      number: 7,
      title: "Produzione orale",
      kind: "parte orale",
      type: "oral",
      points: 15,
      instructions: "Registra UN messaggio vocale per l'insegnante (circa 2 minuti) rispondendo alle seguenti domande.",
      questions: [
        "Racconta come hai trascorso il tuo ultimo compleanno o un'altra festa importante.",
        "Parla dei tuoi progetti per il prossimo anno (lavoro, studio, viaggi).",
        "Dai un consiglio a un amico o un'amica che si sente stressato/a per il lavoro.",
      ],
      rubric: [
        { key: "fluidita", name: "Fluidità e pronuncia", max: 5 },
        { key: "grammatica", name: "Correttezza grammaticale", max: 5 },
        { key: "lessico", name: "Ricchezza lessicale e capacità di esprimere idee", max: 5 },
      ],
    },
  ],
};

module.exports = { content };
